### ISSUE TITLE
Which JDK Version Should Be Used To Compile GradleRIO Projects?

### ISSUE THREAD

**Issue by TheArchNemesis** [wpilibsuite/GradleRIO#241]
Hello
One of my team's projects is a library that contains utility classes that extend WPILib. Recently, we tried to make this library work with gradle. and while it seems to mostly work fine we ran into lots of issues with code that was built using different versions of the JDK. For example, the third-party opencv package is compiled for java 11, but the rest of WPILib is compiled for java 8, and as I understand the code that we upload onto the RoboRIO should target java 8 as well.  
Could someone please explain to me what is happening and which version of the JVM should my team target while compiling and deploying our code?

**Comment by PeterJohnson** [comment]
For the season, everything will be Java 11, so that’s what the beta is using and what our latest published opencv packages are compiled with, etc.  The “alpha test” release uses Java 8, but if you want opencv you have to target the alpha test release opencv dependencies, not the latest ones we have published.

**Comment by TheArchNemesis** [comment]
Thank you very much!
