### ISSUE TITLE
SmartDashboard/Shuffleboard installed by Gradle don't start

### ISSUE THREAD

**Issue by e-bonner** [wpilibsuite/GradleRIO#392]
After installing tools with gradlew commands, some of them don't work.

- RobotBuilder: Works
- OutlineViewer: Launches but does nothing after clicking "Start"
- SmartDashboard: Crashes (stacktrace attached as [sdcrash.log](https://github.com/wpilibsuite/GradleRIO/files/4024117/sdcrash.log))
- Shuffleboard: Displays splash then crashes with a similar error to SmartDashboard
- PathWeaver: Appears to work

**Comment by ThadHouse** [comment]
Did you use the installer? If you did not use the installer, you will need the latest VS 2019 C++ redistributable in order to run the desktop tools.

https://support.microsoft.com/en-us/help/2977003/the-latest-supported-visual-c-downloads

Download the right one for your JDK, likely 64 bit, but it doesn't hurt to install both the 32 bit and 64 bit ones.
